### ISSUE TITLE
不同地区的BING_API

### ISSUE THREAD

**Issue by it985** [niumoo/bing-wallpaper#10]
com/wdbyte/bing/Wallpaper.java  23行
原：    private static String BING_API = "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&nc=1612409408851&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160";
我想改成不同地区：比方说de-DE,en-CA.en-US等地区，应该怎么写

**Comment by niumoo** [comment]
目前看这个API 是根据请求地自动区分地区响应的~

**Comment by jaesteeeen** [comment]
> com/wdbyte/bing/Wallpaper.java 23行 原： private static String BING_API = "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&nc=1612409408851&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160"; 我想改成不同地区：比方说de-DE,en-CA.en-US等地区，应该怎么写

加一个setmkt参数
bing_api = "https://global.bing.com/HPImageArchive.aspx?format=js&idx=0&n=9&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160&setmkt={}&setlang=en"
可用的地区
regions = ["en-US", "zh-CN", "ja-JP", "en-IN", "pt-BR", "fr-FR", "de-DE", "en-CA", "en-GB", "it-IT", "es-ES", "fr-CA"]

**Comment by it985** [comment]
> > com/wdbyte/bing/Wallpaper.java 23行 原： private static String BING_API = "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&nc=1612409408851&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160"; 我想改成不同地区：比方说de-DE,en-CA.en-US等地区，应该怎么写
> 
> 加一个setmkt参数 bing_api = "[https://global.bing.com/HPImageArchive.aspx?format=js&idx=0&n=9&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160&setmkt={}&setlang=en](https://global.bing.com/HPImageArchive.aspx?format=js&idx=0&n=9&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160&setmkt=%7B%7D&setlang=en)" 可用的地区 regions = ["en-US", "zh-CN", "ja-JP", "en-IN", "pt-BR", "fr-FR", "de-DE", "en-CA", "en-GB", "it-IT", "es-ES", "fr-CA"]
感谢
