### ISSUE TITLE
是否考虑增加一个中国时区的选项?

### ISSUE THREAD

**Issue by ZhouMoon** [niumoo/bing-wallpaper#11]
由于我手机、电脑默认是中国时区的图, 想把大佬主页作为新标签页,但图差几个小时😊😊

**Comment by niumoo** [comment]
感谢支持，我加上中国区壁纸页面，完成后再回复你。

**Comment by niumoo** [comment]
已上线~
https://bing.wdbyte.com/zh-cn/
