### ISSUE TITLE
研究了一下，发现可能有多个接口

### ISSUE THREAD

**Issue by byddgithubzh** [niumoo/bing-wallpaper#12]
从bing.com网页抓包

https://cn.bing.com/hp/api/model
ZH-CH，必应国内版
https://cn.bing.com/hp/api/model?ensearch=1
ZH-EN，必应国内国际版
https://www.bing.com/hp/api/model
EN-US，必应真国际版
![image](https://user-images.githubusercontent.com/78755339/218038657-2f871e55-5f44-47c7-bb44-a5cf576c20a4.png)

前两个接口似乎不限制IP。第三个接口，似乎是按照IP归类的，使用非国内IP请求。
2023-02-10请求，三个接口请求到的部分时间结果有不同。
或许还有更多的接口，代理池子不够了，您有空了再研究一下。

还有，您wallpaper.java 中的
private static String BING_API = "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&nc=1612409408851&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160"
接口，是从什么地方抓的？

**Comment by niumoo** [comment]
感谢提供接口。
private static String BING_API = "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&nc=1612409408851&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160"

这个接口直接从主页网络请求追出来的~，不过这个接口是根据请求 IP 来处理的，因为我使用 Github Actions 自动抓取，所以每次都是国外壁纸

**Comment by byddgithubzh** [comment]
了解，但我还想知道具体是哪个页面或者是软件中抓出的，麻烦您提供下具体的url、软件名。

**Comment by byddgithubzh** [comment]
> 感谢提供接口。 private static String BING_API = "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=10&nc=1612409408851&pid=hp&FORM=BEHPTB&uhd=1&uhdwidth=3840&uhdheight=2160"
> 
> 这个接口直接从主页网络请求追出来的~，不过这个接口是根据请求 IP 来处理的，因为我使用 Github Actions 自动抓取，所以每次都是国外壁纸

了解，但我还想知道具体是哪个页面或者是软件中抓出的，麻烦您提供下具体的url、软件名。

**Comment by niumoo** [comment]
![image](https://user-images.githubusercontent.com/26371673/218264930-59143a18-54e9-4e9f-aac8-7736915bad22.png)
可以看下这篇文章：https://www.wdbyte.com/2021/03/bing-wallpaper-github-action/

**Comment by niumoo** [comment]
已上线~
https://bing.wdbyte.com/zh-cn/
