### ISSUE TITLE
UHD 4k size being restricted to HD

### ISSUE THREAD

**Issue by barretts** [niumoo/bing-wallpaper#14]
Seems like the UHD version is sending 1920x1080 now and has been doing so for several days now. I was hoping you had some ideas or info about it.

**Comment by niumoo** [comment]
Let me see

**Comment by niumoo** [comment]
Fixed

**Comment by baractald** [comment]
Although the fixed photo size is 4K, but it seems just 1080p enlarged, not as HD as before.

**Comment by liyanjie8712** [comment]
There is no need to solve it, because a HD pic would have appeared in the UHD resource as same name like “xxxx_UHD.ext”
