### ISSUE TITLE
壁纸变成实际1920x1080的分辨率

### ISSUE THREAD

**Issue by ddddavid-he** [niumoo/bing-wallpaper#15]
从2023/03/25日图片开始bing返回的url对应的UHD图像就只有1920x1080的分辨率了，这个项目里请求的4k分辨率图片实际上是1080p扩展得到的图像

**Comment by niumoo** [comment]
> 从2023/03/25日图片开始bing返回的url对应的UHD图像就只有1920x1080的分辨率了，这个项目里请求的4k分辨率图片实际上是1080p扩展得到的图像

我也发现了这个问题，目前还没有找到响应的可以获取到原图的 API，Bing 貌似对 API  进行了限制

**Comment by KrisNie** [comment]
试试这个 repo ：[wallpaper-database](https://github.com/mouday/wallpaper-database)

**Comment by niumoo** [comment]
> 试试这个 repo ：[wallpaper-database](https://github.com/mouday/wallpaper-database)
这个仓库也是 1920xx1080 的图片了，现在目前还没有发现4 K 接口
<img width="944" alt="image" src="https://github.com/niumoo/bing-wallpaper/assets/26371673/faa03715-a76f-43c1-bb02-247ea86da72e">

**Comment by ddddavid-he** [comment]
最近的图片似乎又全部回归4K+了，估计前一段时间是微软自己都没拿到4K的图

**Comment by niumoo** [comment]
> 最近的图片似乎又全部回归4K+了，估计前一段时间是微软自己都没拿到4K的图

BUG 无处不在~
