### ISSUE TITLE
感谢！

### ISSUE THREAD

**Issue by wswn** [niumoo/bing-wallpaper#16]
喜欢的一张壁纸Bing居然过期了，找到这里，发现过往的都有！！！想一张一张试，发现浏览器好像没权限，所以写了个软件，
[JSWallPaper](https://github.com/wswn/JSWallPaper)，应该会方便一些。
再次感谢！

**Comment by niumoo** [comment]
点赞，很棒的功能~

**Comment by wswn** [comment]
![image](https://user-images.githubusercontent.com/9503473/233051469-0f809f67-387a-4fa6-a0b9-695becceb133.gif)
