### ISSUE TITLE
add option to set custom user video as wallpaper in edge

### ISSUE THREAD

**Issue by jees47** [niumoo/bing-wallpaper#17]
its not a bug, i want to request for a new feature. add option to set custom video as wallpaper like image does

**Comment by niumoo** [comment]
I apologize for the delayed response. Do you want the image to fill the entire webpage or do you want it to be like the current page with added text? If you choose to customize the image, what would you like the text content to be? Would you like to customize it as well?

**Comment by jees47** [comment]
not image, video as a background
