### ISSUE TITLE
请问大佬，这个怎么用呢？直接就在你的github页面下载码？还是把仓库clone下来之后怎么操作？

### ISSUE THREAD

**Issue by roverway** [niumoo/bing-wallpaper#2]
不懂java。。
有没有批量下载的方式呢？
再就是21年2月1号之前的是什么原因没有呢？

**Comment by niumoo** [comment]
你是想批量下载这些图片吗？

21年2月1号之前的是什么原因没有呢？
  是因为这个自动抓取的程序我是21年2月1号发布的哈，之前的壁纸并没有补抓。

**Comment by roverway** [comment]
> 你是想批量下载这些图片吗？
> 
> 21年2月1号之前的是什么原因没有呢？
> 是因为这个自动抓取的程序我是21年2月1号发布的哈，之前的壁纸并没有补抓。

我想最好是能批量下载4k的壁纸，不能批量的话，每天下载一张也行，但是我不会用你这个代码。。

**Comment by niumoo** [comment]
现在每天抓取的壁纸，都已经归档在这个文件里了
[https://github.com/niumoo/bing-wallpaper/blob/main/bing-wallpaper.md](
https://github.com/niumoo/bing-wallpaper/blob/main/bing-wallpaper.md)
里面是 Markdown 语法的图片链接，你可以直接通过链接下载，也可以用你熟悉的语言，进行下载。

**Comment by niumoo** [comment]
[https://github.com/niumoo/bing-wallpaper](https://github.com/niumoo/bing-wallpaper)
首页里的 download 4k 按钮也可以保存
