### ISSUE TITLE
批量下载

### ISSUE THREAD

**Issue by EchoGroot** [niumoo/bing-wallpaper#5]
你好！可否支持批量下载啊，我有这样的需求，需要很多本地图片，用于平时测试，或者用于自动更换电脑壁纸。

**Comment by niumoo** [comment]
好想法，后续来看看下载功能放到哪里比较好。🌹🌹🌹

**Comment by orangeeeen** [comment]
grep -Ev "^$|#" bing-wallpaper.md | sed "s/\(.*\) |.*](\(.*\))/wget -O \1.jpg \2/g" > download.sh
bash download.sh
