### ISSUE TITLE
github.io展示

### ISSUE THREAD

**Issue by 8838** [niumoo/bing-wallpaper#7]
后面如果能把这个仓库直接绑定域名做成github pages网站。把壁纸展示在网页上就更好了

**Comment by niumoo** [comment]
> 现在的仓库绑定域名可以展示README.md的内容。但排版有些问题。希望作者能针对性优化一下。谢谢啦

这个我是知道的，后面我可以搞个 github pages 的网页或者直接注册个域名来发布一下。貌似挺多人喜欢这些壁纸。

**Comment by 8838** [comment]
感谢作者，github仓库页面的排版形式非常棒，只不过发布成网页后有一些兼容错误，希望形式还是不变只是兼容一下单网页，看到这个项目后我特别喜欢，我有些等不及了我想自己修改一下网页排版，但是不知道怎么触发Actions 任务，而且好像当天修改时间(UTC+0)也不会触发任务

**Comment by niumoo** [comment]
> 感谢作者，github仓库页面的排版形式非常棒，只不过发布成网页后有一些兼容错误，希望形式还是不变只是兼容一下单网页，看到这个项目后我特别喜欢，我有些等不及了我想自己修改一下网页排版，但是不知道怎么手动触发Actions 任务，而且好像当天修改时间(UTC+0)也不会触发任务

上个周末抽出时间对项目进行了优化，并简单做了个在线网站 。
可以通过地址：https://bing.wdbyte.com/ 访问浏览。
源码也已经开源，欢迎讨论交流。

**Comment by midpoint** [comment]
可以打开，但是看不到小图

**Comment by it985** [comment]
> > 己谢い，github仓い页欢い，只い页い页错误い，い，只い，只い，，，2010，201只，200，看い项い，'）-いいい别いい， いい页い，且 任务 い，任务，，
> 
> 上个周末抽出时间对项目进行了优化，并简单做了个在线网站 。址 [https://bing.wdbyte.com/ 访浏览](https://bing.wdbyte.com/). 码 欢迎讨交い
你好，我fork你的该项目，请问 bing.wdbyte.com 是怎么部署的？方便告知一下吗
