### ISSUE TITLE
bing 壁纸是不是有时候不更新

### ISSUE THREAD

**Issue by 7peanuts** [niumoo/bing-wallpaper#8]
我看主页 10.7 号的没有。
我目前在用微软自己的 bing wallpaper 软件，最近这三个月发现，经常会有不更新的时候，每个月总是缺个五六张，不知道是不是地区的原因。

**Comment by niumoo** [comment]
正常应该不会，还没有遇到过。这个项目里的 10.7 号的没有，原因我看了下，当时BING接口报错了，没有抓取下来导致的，我看看有没有办法补上去。

**Comment by 7peanuts** [comment]
嗯，多谢，那看来应该是 bing 软件的问题，已经不用了，水印是其次，主要是没有收藏功能，试了下拾光还不错。
